# Generated by Django 4.2.16 on 2026-08-06 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('matched_partner_id', models.UUIDField()),
                ('confidence_score', models.FloatField()),
                ('factors', models.JSONField(default=dict)),
                ('was_successful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('recommendation', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('action_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('model_used', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Embedding metadata',
            },
        ),
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_id', models.CharField(max_length=100)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('model', models.CharField(max_length=50)),
                ('prompt_text', models.TextField()),
                ('response', models.TextField()),
                ('latency_ms', models.IntegerField()),
                ('tokens_used', models.IntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
